/*export const HOMEPAGE_LOAD_START = 'HOMEPAGE_LOAD_START';
export const HOMEPAGE_LOAD_SUCCESS = 'HOMEPAGE_LOAD_SUCCESS';
export const HOMEPAGE_LOAD_FAIL = 'HOMEPAGE_LOAD_FAIL';*/

/*
export const HOMEPAGE_LOAD_START = 'HOMEPAGE_LOAD_START';
export const HOMEPAGE_LOAD_SUCCESS = 'HOMEPAGE_LOAD_SUCCESS';
export const HOMEPAGE_LOAD_FAIL = 'HOMEPAGE_LOAD_FAIL';*/

export const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT';
export const CART_ADD_PRODUCT_START = 'CART_ADD_PRODUCT_START';
export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS';
export const CART_ADD_PRODUCT_FAIL = 'CART_ADD_PRODUCT_FAIL';
