export const INIT_APP_START = "INIT_APP_START";
export const INIT_APP_SUCCESS = "INIT_APP_SUCCESS";
export const INIT_APP_FAIL = "INIT_APP_FAIL";

export const CART_ADD_PRODUCT_START = "CART_ADD_PRODUCT_START";
export const CART_ADD_PRODUCT_SUCCESS = "CART_ADD_PRODUCT_SUCCESS";
export const CART_ADD_PRODUCT_FAIL = "CART_ADD_PRODUCT_FAIL";

export const CART_DELETE_PRODUCT_START = "CART_DELETE_PRODUCT_START";
export const CART_DELETE_PRODUCT_SUCCESS = "CART_DELETE_PRODUCT_SUCCESS";
export const CART_DELETE_PRODUCT_FAIL = "CART_DELETE_PRODUCT_FAIL";

export const CART_SET_PRODUCT_QUANTITY_START = "CART_SET_PRODUCT_QUANTITY_START";
export const CART_SET_PRODUCT_QUANTITY_SUCCESS = "CART_SET_PRODUCT_QUANTITY_SUCCESS";
export const CART_SET_PRODUCT_QUANTITY_FAIL = "CART_SET_PRODUCT_QUANTITY_FAIL";

export const PRODUCTS_LOAD_START = 'PRODUCTS_LOAD_START';
export const PRODUCTS_LOAD_SUCCESS = 'PRODUCTS_LOAD_SUCCESS';
export const PRODUCTS_LOAD_FAIL = 'PRODUCTS_LOAD_FAIL';

export const CART_LOAD_START = 'CART_LOAD_START';
export const CART_LOAD_SUCCESS = 'CART_LOAD_SUCCESS';
export const CART_LOAD_FAIL = 'CART_LOAD_FAIL';