export const CART_ADD_PRODUCT_START = "CART_ADD_PRODUCT_START";
export const CART_ADD_PRODUCT_SUCCESS = "CART_ADD_PRODUCT_SUCCESS";
export const CART_ADD_PRODUCT_FAIL = "CART_ADD_PRODUCT_FAIL";

export const CART_DELETE_PRODUCT_START = "CART_DELETE_PRODUCT_START";
export const CART_DELETE_PRODUCT_SUCCESS = "CART_DELETE_PRODUCT_SUCCESS";
export const CART_DELETE_PRODUCT_FAIL = "CART_DELETE_PRODUCT_FAIL";

export const CART_SET_PRODUCT_QUANTITY_START = "CART_SET_PRODUCT_QUANTITY_START";
export const CART_SET_PRODUCT_QUANTITY_SUCCESS = "CART_SET_PRODUCT_QUANTITY_SUCCESS";
export const CART_SET_PRODUCT_QUANTITY_FAIL = "CART_SET_PRODUCT_QUANTITY_FAIL";